name: Build

on:
  push:
    branches:
      - build

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        electron: [7.3.2, 9.1.0]
        include:
          - electron: 7.3.2
            abi: 75
          - electron: 9.1.0
            abi: 80

    name: Build for ${{ matrix.os }}-${{ matrix.abi }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Installing needed Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      - name: Install needed Windows dependencies
        if: matrix.os == 'windows-latest'
        run: choco install llvm

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v2
        id: cargo-cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: yarn

      - name: build for electron@${{ matrix.electron }}
        run: |
          yarn add electron@${{ matrix.electron }}
          yarn add electron-build-env
          yarn add neon-cli
          yarn build
          cp native/index.node build/${{ matrix.os }}-${{ matrix.abi }}.node

      - name: remove uncessary dependencies
        run: |
          yarn remove electron
          yarn remove electron-build-env
          yarn remove neon-cli

      - name: push to repository
        run: |
          git diff
          git config --global user.email "chenxin.lan.76@gmail.com"
          git config --global user.name "YXL"
          git pull
          git add -A
          git commit -m "🔧build(${{ matrix.os }}-${{ matrix.abi }})" || exit 0
          git push
