on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Release Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13"
      - run: yarn
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: yarn test

  package:
    runs-on: ubuntu-latest
    needs: test
    name: Package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13"
      - run: yarn
      - run: npm install -g vsce
      - run: vsce package
      - run: echo ::set-env name=VSIX_PATH::$(find . -maxdepth 1 -type f -iname "*.vsix" | head -1)
      - run: echo ::set-env name=VSIX_NAME::$(basename $(find . -maxdepth 1 -type f -iname "*.vsix" | head -1))
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ env.VSIX_PATH }}
          name: ${{ env.VSIX_NAME }}

  release:
    runs-on: ubuntu-latest
    needs: package
    name: Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13"
      - run: yarn
      - run: npm install -g vsce
      - run: vsce package
      - run: echo ::set-env name=VSIX_PATH::$(find . -maxdepth 1 -type f -iname "*.vsix" | head -1)
      - run: echo ::set-env name=VSIX_NAME::$(basename $(find . -maxdepth 1 -type f -iname "*.  vsix" | head -1))
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: See [CHANGE LOG](https://github.com/YXL76/cloudmusic-vscode/blob/master/CHANGELOG.  md) for details.
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.VSIX_PATH }}
          asset_name: ${{ env.VSIX_NAME }}
          asset_content_type: application/zip
      - run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
